### PR TITLE
Modify blog logo 

### PR DESCRIPTION
**Pull request by JosephineAkello**
Update Logo

### CODE REVIEW

**Comment by TheBeachMaster** [comment]
Is this still WIP? 

If not update PR title

**Comment by JosephineAkello** [comment]
> Is this still WIP?
> 
> If not update PR title

Yes @TheBeachMaster , need a way to change the black part of the SVG to maroon. Have ideas?

**Comment by TheBeachMaster** [comment]
Try https://boxy-svg.com/app

The image link is https://raw.githubusercontent.com/Tambua-WomenInTech-Blog/womenintechblogdev/be245746a32979529e0c8bec9cba5474da583d61/assets/images/logo.svg

Go to `File>New From URL`

Screenshot_20220510_000457

**Comment by JosephineAkello** [comment]
> 

Awesome @TheBeachMaster , This is very helpful. Thank youuu!! : )

**Review by TheBeachMaster — APPROVED** [review]

**Pull request merged**
